cli:
  build: cli
  links:
    - db
    - rabbit
    - memcache
    - keystone
    - glanceregistry
    - glanceapi
    - novacontroller
data:
  build: data
  volumes:
    - data/mysql:/var/lib/mysql
    - data/rabbitmq:/var/lib/rabbitmq
    - data/glance:/var/lib/glance/images
    - data/apache2_logs:/var/log/apache2
keystone:
  build: keystone
  volumes:
    - keystone:/keystone-src
  hostname: keystone
  ports:
    - 5000
    - 35357
  links:
    - db
    - rabbit
    - memcache
  environment:
    MYSQL_ROOT_PASSWORD: firma8isdead
glanceregistry:
  build: glance-registry
  hostname: glanceregistry
  ports:
    - 9191
  links:
    - db
    - rabbit
    - memcache
    - keystone
  environment:
    MYSQL_ROOT_PASSWORD: firma8isdead
glanceapi:
  build: glance-api
  hostname: glanceapi
  ports:
    - 9292
  volumes_from:
    - data
  links:
    - db
    - rabbit
    - memcache
    - keystone
    - glanceregistry
  environment:
    MYSQL_ROOT_PASSWORD: firma8isdead
novacontroller:
  build: nova-controller
  hostname: novacontroller
  ports:
    - 8774
  links:
    - db
    - rabbit
    - memcache
    - keystone
    - glanceapi
  privileged: true
  environment:
    MYSQL_ROOT_PASSWORD: firma8isdead
novanode:
  build: nova-node
  hostname: novanode
  links:
    - rabbit
    - glanceapi
    - keystone
    - novacontroller
  privileged: true
horizon:
  build: horizon
  hostname: horizon
  ports:
    - 80
  links:
    - keystone
    - novacontroller
    - glanceapi
  volumes_from:
    - data
db:
  image: mariadb:5.5.45
  environment:
    MYSQL_ROOT_PASSWORD: firma8isdead
  ports:
    - 3306
  volumes_from:
    - data
rabbit:
  image: rabbitmq:3.5.4
  environment:
    RABBITMQ_DEFAULT_USER: openstack
    RABBITMQ_DEFAULT_PASS: firma8isdead
  volumes_from:
    - data
memcache:
  image: memcached:1.4.24
